name: Automate Test Run

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Choose the functionality to be automated
        options:
          - test_one
          - test_two
jobs:
  test_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
#         with:
#           path: ${{ env.pythonLocation }}
#           key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}


      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run ${{ inputs.choice }} Test Script
        run: pytest tests/test_script.py::${{ inputs.choice }}

