name: Automate Test Run

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Choose the functionality to be automated
        options:
          - test_one
          - test_two
jobs:
  test_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Activate Virtual Environment
        run: |
          if [ -f .env ]; then source .env\bin\
          activate; fi
      
      - name: Run ${{ inputs.choice }} Test Script
        run: pytest tests/test_script.py::${{ inputs.choice }}

