name: Basic Setup

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3

      - name: Create Virtual Environment
        run: python3 -m venv .env
        
      - name: Activate Virtual Environment
        run: |
          if [ -f .env ]; then source .env\bin\
          activate; fi

                
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
